#!/bin/bash

if [[ -z $STOW_FOLDERS ]]; then STOW_FOLDERS="bash,neovim,tmux,xinit,git"; fi
if [[ -z $DOTFILES ]]; then DOTFILES=$HOME/.dotfiles; fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
